from __future__ import annotations
from pathlib import Path
import json, shutil

MCP_SNIPPET='''# Generated by Dispatch\n# Review in the Setup GUI before applying to Hermes.\nmcp_servers:\n  filesystem_projects:\n    command: npx\n    args: [\"-y\", \"@modelcontextprotocol/server-filesystem\", \"{projects}\"]\n  context7:\n    command: npx\n    args: [\"-y\", \"@upstash/context7-mcp\"]\n  playwright:\n    command: npx\n    args: [\"-y\", \"@playwright/mcp@latest\", \"--headless\"]\n  penpot:\n    command: npx\n    args: [\"-y\", \"@penpot/mcp@stable\"]\n'''

def resolve_agent_model(agent, model_source, recommendation, frontier_models):
    """Work out which concrete model an agent's role should be pointed at, given the
    model source the person picked in the wizard (local / frontier / hybrid)."""
    role = agent.get("model_capability", "general")
    if model_source == "frontier":
        f = (frontier_models or {}).get(role)
        return f"{f['provider']}: {f['model']}" if f and f.get("model") else "(frontier model not set)"
    if model_source == "hybrid":
        f = (frontier_models or {}).get(role)
        if f and f.get("model"):
            return f"{f['provider']}: {f['model']}"
    local = (recommendation or {}).get(role)
    return local["id"] if local else "(no local model recommended)"

def build_agent_setup_guide(org, recommendation, model_source, frontier_models):
    """A per-agent Markdown checklist for manually creating each role inside Hermes,
    for whenever Hermes doesn't (or can't yet) create them automatically from
    agent-organization.json."""
    lines = ["# Hermes agent setup checklist", "",
             f"Deployment target(s): {', '.join(org.get('project_types', []))} — complexity: {org.get('complexity','?')}",
             f"Model source: {model_source}", "",
             "For each role below that Hermes doesn't already have, create a new agent with this name, "
             "point it at the listed model, and give it access to the listed tools. Department and level are "
             "there to help you organize Hermes's agent list the same way the studio does.", ""]
    for a in org.get("agents", []):
        model = resolve_agent_model(a, model_source, recommendation, frontier_models)
        lines += [
            f"## {a['name']}",
            f"- **Department:** {a['department']}",
            f"- **Level:** {a['level']}",
            f"- **Model:** {model}",
            f"- **Tools:** {', '.join(a.get('tools', [])) or 'none listed'}",
            f"- **Reports to:** {a.get('reports_to') or 'top of the organization'}",
            "",
        ]
    return "\n".join(lines)

def generate(home, org, recommendation, model_source="local", frontier_models=None):
    out=Path(home)/"generated";out.mkdir(parents=True,exist_ok=True)
    projects=Path(home)/"projects";projects.mkdir(exist_ok=True)
    (out/"hermes-mcp.yaml").write_text(MCP_SNIPPET.format(projects=projects))
    (out/"agent-organization.json").write_text(json.dumps(org,indent=2))
    (out/"model-plan.json").write_text(json.dumps(recommendation,indent=2))
    guide=build_agent_setup_guide(org, recommendation, model_source, frontier_models)
    (out/"agent-setup-guide.md").write_text(guide)
    return {"mcp":str(out/"hermes-mcp.yaml"),"organization":str(out/"agent-organization.json"),"models":str(out/"model-plan.json"),"agent_guide":str(out/"agent-setup-guide.md"),"agent_guide_text":guide}

def integration_status():
    cfg=Path.home()/".hermes"/"config.yaml"
    if not cfg.exists(): return {"mode":"not_found","message":"Hermes config was not found. Generated integration files are ready."}
    text=cfg.read_text(errors='ignore')
    if "mcp_servers:" in text:
        return {"mode":"manual_merge","message":"Existing mcp_servers section detected. Safe automatic merge is intentionally disabled in v0.1; use the generated candidate after backup/review."}
    return {"mode":"append_candidate","message":"Hermes config exists and no mcp_servers section was detected. The generated MCP block can be appended after backup, but version-specific validation is still recommended."}
